### PR TITLE
crates.io release

### PR DESCRIPTION
**Pull request by kornelski**
This is the only issue I've found testing gif 0.13, so once that is released, gif will be ready too.

### CODE REVIEW

**Comment by kornelski** [comment]
@fintelia Could you make a release of weezl?

**Comment by kornelski** [comment]
@HeroicKatora could you make a release of weezl?

**Comment by fintelia** [comment]
I can publish the release, but would you be able to add a changelog entry first?

**Comment by kornelski** [comment]
Added changelog

**Comment by fintelia** [comment]
Published!

**Pull request merged**
